# Generated by Django 6.0.3 on 2026-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Product',
        ),
    ]
